version: "3.7"
services:
  docker-demo:
    image: docker-demo
    container_name: docker-demo
    restart: unless-stopped
    command: 
      - "--access-logfile=-"
    environment:
      - "REDIS_HOST=redis"
    ports:
      - "80:8080"
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    volumes:
      - type: volume
        source: redis
        target: /data
volumes:
  redis:
